// Classes and structures being serialized

// Generated by ProtocolBuffer
// - a pure c# code generation implementation of protocol buffers
// Report bugs to: https://silentorbit.com/protobuf/

// DO NOT EDIT
// This file will be overwritten when CodeGenerator is run.
// To make custom modifications, edit the .proto file and add //:external before the message line
// then write the code and the changes in a separate file.
using System;
using System.Collections.Generic;

namespace AccountProto
{
    /// <summary> ���</summary>
    public partial class CSReservedMsg
    {
        public int Reserved { get; set; }

    }

    /// <summary> ע���˺ţ��ͻ���-���˺ŷ�����</summary>
    public partial class CARegAccountC
    {
        public string Name { get; set; }

        public string PasswdMd5 { get; set; }

        public string Mail { get; set; }

        /// <summary> ����</summary>
        public string Mobile { get; set; }

    }

    /// <summary> ע���˺ţ��˺ŷ�����-���ͻ���</summary>
    public partial class CARegAccountS
    {
        public int Result { get; set; }

        /// <summary> 0:ע��ɹ��� 1�����ظ����֣� 2�����ֲ��Ϸ�</summary>
        public uint Uin { get; set; }

    }

    public partial class CANewAccountC
    {
        public string DeviceId { get; set; }

    }

    public partial class CANewAccountS
    {
        public int Result { get; set; }

        /// <summary> 0: �������˺ţ� 1: ����֮ǰ���豸�������˺ţ�  2��ʧ��</summary>
        public uint Uin { get; set; }

        /// <summary> ����ʹ��_uin���û�����¼</summary>
        public string PasswdMd5 { get; set; }

    }

    public partial class CAServerListC
    {
        public int Version { get; set; }

        /// <summary> �������б�İ汾��</summary>
        public int Svgroup { get; set; }

    }

    public partial class CAServerDesc
    {
        public int Id { get; set; }

        /// <summary> game server id</summary>
        public int Status { get; set; }

        /// <summary> game server status, 0:ά���� 1�������� 2����æ�� 3�������� �����4λ����Ϊ�Ƽ�</summary>
        public string Name { get; set; }

        /// <summary> ���ͻ��˰汾�Ѿ������£� �������ݲ�����</summary>
        public string Addr { get; set; }

        public int Port { get; set; }

    }

    public partial class CAServerListS
    {
        public int Version { get; set; }

        /// <summary> �������µķ������б�汾��</summary>
        public List<AccountProto.CAServerDesc> DescArray { get; set; }

    }

    public partial class CAAuthAccountC
    {
        public AccountProto.AccountPlatform Platform { get; set; }

        /// <summary> AccountPlatform, ƽ̨ID: �Լ���׿�� �Լ�ƻ���� 360��91</summary>
        public string Name { get; set; }

        /// <summary> ����ͨ��name����uin����֤�˺�</summary>
        public uint Uin { get; set; }

        /// <summary> �û���uin</summary>
        public string PasswdMd5 { get; set; }

        /// <summary> �����md5</summary>
        public uint Cpid { get; set; }

        /// <summary> cp���̵�ID</summary>
        public uint Appid { get; set; }

        /// <summary> app��ID</summary>
        public string Sid { get; set; }

    }

    public partial class CAAuthAccountS
    {
        public int Result { get; set; }

        /// <summary> 0: ��֤�ɹ�,  1:ʧ��</summary>
        public string Sid { get; set; }

        /// <summary> session id</summary>
        public uint Uin { get; set; }

    }

    /// <summary> ��Ϸ��������֤�˺ţ���Ϸ������-���˺ŷ�����</summary>
    public partial class GAAuthAccountC
    {
        public uint Uin { get; set; }

        public string Sid { get; set; }

        public uint Clientid { get; set; }

    }

    /// <summary> ��Ϸ��������֤�˺ţ��˺ŷ�����-����Ϸ������</summary>
    public partial class GAAuthAccountS
    {
        public int Result { get; set; }

        public uint Clientid { get; set; }

        public uint Uin { get; set; }

        public string Info { get; set; }

    }

    public partial class GAVerifyBuyC
    {
        public int Platform { get; set; }

        /// <summary> ����ƽ̨</summary>
        public uint Uin { get; set; }

        /// <summary> ���uin</summary>
        public string Itemid { get; set; }

        /// <summary> ��Ʒid</summary>
        public string Receipt { get; set; }

        /// <summary> app store���ص�receipt��  91���̵����ɵĶ������кţ�32λguid)</summary>
        public int Price { get; set; }

    }

    public partial class GAVerifyBuyS
    {
        public int Result { get; set; }

        /// <summary> 0: ȷ�ϳɹ��� 1: ȷ��ʧ��</summary>
        public uint Uin { get; set; }

        public string Itemid { get; set; }

        public string Receipt { get; set; }

    }

    /// <summary> ��accountserver����gameserver</summary>
    public partial class GABuyNotifyC
    {
        public AccountProto.PayPlatform Platform { get; set; }

        /// <summary> ����ƽ̨</summary>
        public uint Uin { get; set; }

        public string Itemid { get; set; }

        public string Receipt { get; set; }

        public int Count { get; set; }

        /// <summary> ��������</summary>
        public int Money { get; set; }

    }

    /// <summary> gameserver���ص�</summary>
    public partial class GABuyNotifyS
    {
        public int Result { get; set; }

        /// <summary> 0����ɹ���  1��uin������,  2: itemid������,  3: �۸�Բ���</summary>
        public string Receipt { get; set; }

    }

    public partial class GAReportStatusC
    {
        public int Nconn { get; set; }

        /// <summary> ������</summary>
        public int Nlogin { get; set; }

        /// <summary> ��½��</summary>
        public uint Servertime { get; set; }

        /// <summary> ������ʱ��</summary>
        public int Memory { get; set; }

        /// <summary> ռ���ڴ棺kb</summary>
        public int Cpu { get; set; }

    }

    public enum MsgType
    {
        AP_RESERVED = 0,
        CA_REG_ACCOUNT = 1,
        /// <summary> �ͻ���ȥaccenterע�������ʺ�</summary>
        CA_NEW_ACCOUNT = 2,
        /// <summary> ��accenter����һ�������˺�</summary>
        CA_SERVER_LIST = 3,
        /// <summary> �õ��������б�</summary>
        CA_AUTH_ACCOUNT = 4,
        /// <summary> �ͻ���ȥaccenter��֤�����˺�</summary>
        GA_AUTH_ACCOUNT = 5,
        /// <summary> ��Ϸ�������ڿͻ��˵�¼ʱȥaccenter��֤</summary>
        GA_VERIFY_BUY = 9,
        /// <summary> ��֤app store�Ĺ���,  ����ƻ���̵꣬ 91ƽ̨</summary>
        GA_REPORT_STATUS = 10,
        /// <summary> �ϱ����������ݣ������������Ƿ�æµ</summary>
        GA_BUY_NOTIFY = 11,
    }


    public enum CAResult
    {
        RE_OK = 0,
        RE_REG_ACCOUNT_EXIST = 1,
        /// <summary> �˺��Ѿ����ڣ� ���ܴ���</summary>
        RE_AUTH_NOACCOUNT = 2,
        /// <summary> �˺Ų����ڣ� ��֤��ͨ��</summary>
        RE_AUTH_WRONG_PWD = 3,
        /// <summary> �������</summary>
        RE_AUTH_LOCKED = 4,
        /// <summary> �˺�����</summary>
        RE_ACCOUNT_ILLEGAL = 5,
        /// <summary> �˺Ų��Ϸ�</summary>
        RE_DATA_WRONG = 99,
        /// <summary> ���ݴ���</summary>
        RE_CONN_OUTSERVER = 100,
    }


    public enum AccountPlatform
    {
        ACCOUNT_DEFALUT = 0,
        /// <summary> ����ȱʡ��ʽ</summary>
        ACCOUNT_360 = 1,
        /// <summary> 360�˺�</summary>
        ACCOUNT_91 = 2,
    }


    public enum PayPlatform
    {
        PAY_DEFAULT = 0,
        /// <summary> ����ȱʡ��ʽ</summary>
        PAY_IOS_STORE = 1,
        /// <summary> ios store�Ĺ���ʽ</summary>
        PAY_GOOGLE_STORE = 2,
        /// <summary> google store�Ĺ���ʽ</summary>
        PAY_91 = 3,
    }


    public enum ServerGroupType
    {
        SVGROUP_DEFAULT = 0,
        /// <summary> ȱʡ�ķ�������</summary>
        SVGROUP_HONGKONG = 1,
    }


}
